### ISSUE TITLE
failed to build from source distribution

### ISSUE THREAD

**Issue by crystina-z** [seanmacavaney/pyautocorpus#1]
Hi! I noticed that when trying to install `pyautocorpus` on machines where no existing wheel is available, it would fail with the following error:
```
$ pip install pyautocorpus # or `pip install pyautocorpus  --no-binary=:all:` on a machine with available wheel
...
    Running setup.py install for pyautocorpus ... error
    ERROR: Command errored out with exit status 1:
     command: /home/czhang/anaconda3/envs/dpr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x5jpwo5w/install-record.txt --single-version-externally-managed --compile --install-headers /home/czhang/anaconda3/envs/dpr/include/python3.7m/pyautocorpus
         cwd: /tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/
    Complete output (14 lines):
    running install
    running build
    running build_ext
    building 'pyautocorpus' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -B /home/czhang/anaconda3/envs/dpr/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPCRE_STATIC -I/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/AutoCorpus/src/common -I/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/AutoCorpus/src/wikipedia -I/home/czhang/anaconda3/envs/dpr/include/python3.7m -c src/pyautocorpus.cpp -o build/temp.linux-x86_64-3.7/src/pyautocorpus.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/pyautocorpus.cpp:4:10: fatal error: Textifier.h: No such file or directory
     #include "Textifier.h"
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/czhang/anaconda3/envs/dpr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bfzv4zc8/pyautocorpus_49f9f38d2ca64edb836b9ce93f4c4ab3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x5jpwo5w/install-record.txt --single-version-externally-managed --compile --install-headers /home/czhang/anaconda3/envs/dpr/include/python3.7m/pyautocorpus Check the logs for full command output.
```
which seems to me is because the submodule `AutoCorpus` was not included? Also if I clone `pyautocorpus` with submodule and build in the cloned repo, the problem could be solved.

**Comment by seanmacavaney** [comment]
Hi Crystina,

Thanks for reporting. Yes, you need to clone the repository with submodules in order to build. This should probably be added to the readme. I’ll see what I can do to add the submodule code to the sdist, somehow this was missed.

Which platform are you using that doesn’t have a wheel on pypi? It should probably be added to the build.

**Comment by crystina-z** [comment]
Thanks for the prompt reply! I'm using a machine with CentOS 7, x86_64. and python `3.7.9` with `pip 20.3.4`

**Comment by seanmacavaney** [comment]
Installing from sdist should work now (starting v0.1.2). Thanks again for reporting and for the `--no-binary=:all:` trick!

To include CentOS, looks like I'll need to change the bdist from `manylinux` to `manylinux2014`, based on [this source](https://realpython.com/python-wheels/)? Gotta look more into this, but for now, at least it's not broken for sdist.

**Comment by crystina-z** [comment]
great thx! also tested installing on the centos 7 machine and the installation works for 0.1.2 now.

> To include CentOS, looks like I'll need to change the bdist from manylinux to manylinux2014, based on this source? 

yea I guess so, tho I don't have experience preparing wheels :P But I can always help to test if the built wheel works for the cent os 7 platform!

**Comment by seanmacavaney** [comment]
Awesome- thanks! I think I have a build that works for cenos 7. Can you try installing the wheel for v0.1.3 and let me know if it works?

**Comment by crystina-z** [comment]
Just tried, it seems not work if I directly do `pip install pyautocorpus`. Then according to [this](https://stackoverflow.com/a/67548812/13112529), I checked the compatible tags and found it supports all the way from `...manylinux2_6_..` to `...manylinux2_30_..` but exactly not the `...manylinux2_17_..` which is released. So I manually download the [pyautocorpus-0.1.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ](https://files.pythonhosted.org/packages/aa/3f/7b20b030e21b643c77206709c8948929465bbde6bdabcf33c8511eb55221/pyautocorpus-0.1.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) file, and rename it to `...manylinux_2_18..`, then the installation magically successes and the example in readme runs fine.

**Comment by seanmacavaney** [comment]
Thanks for the help! I'm not sure I fully understand the implications of renaming 2_17 to 2_18, but if it works, it works, right?

Can you try installing v0.1.5 on CentOS? It replaces 2_17 wheels with 2_18.

**Comment by crystina-z** [comment]
hi thanks for the follow up! I just tried but sadly it doesn't seem work,  and the supported tags on the platform weirdly changed this time (`2_18` does not shown in the tags this time...). I guess the now the issue is more because of the server I'm using rather than the package side :(

Btw the installation from source always works!

**Comment by seanmacavaney** [comment]
Alright- thanks for trying. It seems easiest just to stick with sdist for CentOS then. There’s a chance of installation problems with the pcre dependency, but we’ll just have to live with that.

Thanks for all the help!
