### ISSUE TITLE
Is pyautocorpus not support the Mac M1 chip?

### ISSUE THREAD

**Issue by ShiiDD** [seanmacavaney/pyautocorpus#3]
```
Collecting pyautocorpus
  Using cached pyautocorpus-0.1.8.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyautocorpus
  Building wheel for pyautocorpus (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'pyautocorpus' extension
      src/Textifier.cpp:40:10: fatal error: 'pcre.h' file not found
      #include <pcre.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyautocorpus
  Running setup.py clean for pyautocorpus
Failed to build pyautocorpus
Installing collected packages: pyautocorpus
  Running setup.py install for pyautocorpus ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyautocorpus did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running install
      /lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'pyautocorpus' extension
      src/Textifier.cpp:40:10: fatal error: 'pcre.h' file not found
      #include <pcre.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyautocorpus

```

**Comment by seanmacavaney** [comment]
Thanks for reporting.

Unfortunately, I do not have an M1 machine to test this on, and [it also isn't supported on Github Actions](https://github.com/actions/virtual-environments/issues/2187) from what I gather, which will make it challenging to have an automated build push this to pypi.

But, based on the error message, it looks like all you gotta do is install the pcre library, which is easy with homebrew:

```bash
brew install pcre
```

(Or alternative instructions [here](https://stackoverflow.com/questions/22555561/error-building-fatal-error-pcre-h-no-such-file-or-directory))

Let me know if this works, and hope this helps!

**Comment by ShiiDD** [comment]
Sorry for the late feedback. After installing pcre, it didn't work. Please see the details below, it did not seem to change anything. When using pip to install ir_database, it seems couldn't find the pcre. But the installation can run smoothly on Windows. 

```python
Building wheel for pyautocorpus (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'pyautocorpus' extension
      src/Textifier.cpp:40:10: fatal error: 'pcre.h' file not found
      #include <pcre.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

 ERROR: Failed building wheel for pyautocorpus
  Running setup.py clean for pyautocorpus
Successfully built lxml lz4
Failed to build pyautocorpus
Installing collected packages: pyautocorpus, lz4, lxml, beautifulsoup4, ir_datasets
  Running setup.py install for pyautocorpus ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyautocorpus did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running install
      /venv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'pyautocorpus' extension
      src/Textifier.cpp:40:10: fatal error: 'pcre.h' file not found
      #include <pcre.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyautocorpus

note: This is an issue with the package mentioned above, not pip.
```

**Comment by seanmacavaney** [comment]
Hi-- the error message `fatal error: 'pcre.h' file not found` suggests that it's not in your `LD_LIBRARY_PATH`. A quick search found this approach: https://stackoverflow.com/a/37568861/406914

**Comment by seanmacavaney** [comment]
Also -- note that pyautocorpus is not needed for any dataset in ir_datasets except [trec-fair-2021](https://ir-datasets.com/trec-fair-2021.html) -- so if you don't need that one, you can skip this requirement.

I'll consider making this an optional dependency of ir_datasets, since it seems to be a hassle to use with M1 Macs.

**Comment by isoboroff** [comment]
I ran into this issue building https://github.com/hltcoe/patapsco.  On my Mac, the telltale error during the pyautocorpus build was:
```
      building 'pyautocorpus' extension
      src/Textifier.cpp:40:10: fatal error: 'pcre.h' file not found
      #include <pcre.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

So, following the instructions in https://stackoverflow.com/a/37568861/406914, I used `clang -v` to find the location to symlink pcre.h into, and it worked.

**Comment by ShiiDD** [comment]
It worked, and I used it the same way as @isoboroff. Thanks!

**Comment by seanmacavaney** [comment]
@ShiiDD @isoboroff -- thanks! Would I be able to bother either of you to help out by building a wheel to allow easier distribution of the package to other folks with an M1 Mac?

**Comment by ShiiDD** [comment]
No problem. If you need, please feel free to contact me.

**Comment by SrK1080** [comment]
I am getting permission denied while i am doing this:
shubhamkarekar@Shubhams-MacBook-Pro ~ % clang -v                          
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
shubhamkarekar@Shubhams-MacBook-Pro ~ % ln -s /opt/homebrew/Cellar/pcre/8.45/include/pcre.h \
      /Library/Developer/CommandLineTools/usr/bin 
 
ln: /Library/Developer/CommandLineTools/usr/bin/pcre.h: Permission denied
shubhamkarekar@Shubhams-MacBook-Pro ~ %

**Comment by Jia-py** [comment]
> Thanks for reporting.
> 
> Unfortunately, I do not have an M1 machine to test this on, and [it also isn't supported on Github Actions](https://github.com/actions/virtual-environments/issues/2187) from what I gather, which will make it challenging to have an automated build push this to pypi.
> 
> But, based on the error message, it looks like all you gotta do is install the pcre library, which is easy with homebrew:
> 
> ```shell
> brew install pcre
> ```
> 
> (Or alternative instructions [here](https://stackoverflow.com/questions/22555561/error-building-fatal-error-pcre-h-no-such-file-or-directory))
> 
> Let me know if this works, and hope this helps!

Same problem showed in installing pyterrier on M1 Mac, but solved with simply `brew install pcre`.

**Comment by seanmacavaney** [comment]
Thanks for the tip!
